<?php

require_once dirname(__FILE__) . '/../../libs/Bootstrap.php';

/**
 * Test class for Bootstrap.
 * Generated by PHPUnit on 2012-06-24 at 01:06:57.
 */
class BootstrapTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Bootstrap
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Bootstrap;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Bootstrap::run
     * @todo Implement testRun().
     */
    public function testRun() {
        // Remove the following lines when you implement this test.
        
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
