<?php

require_once dirname(__FILE__) . '/../../libs/Database.php';

/**
 * Test class for Database.
 * Generated by PHPUnit on 2012-06-24 at 05:52:09.
 */
class DatabaseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Database
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Database;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
